use_frameworks!

platform :ios, '8.0'

target 'LLCategory_Example' do
  pod 'LLCategory', :path => '../'

  target 'LLCategory_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
